--
-- PostgreSQL database dump
--

\restrict 97fezhCafcBjGRABVOCpnOI6PDaQ9fGk2hqa6mB31tWM5UEfccnKVWaf2Cj7soe

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Debian 16.11-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_balance_history; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.account_balance_history (
    id bigint NOT NULL,
    account_id bigint NOT NULL,
    balance numeric(19,4) NOT NULL,
    date date NOT NULL,
    recorded_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.account_balance_history OWNER TO admin;

--
-- Name: account_balance_history_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.account_balance_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_balance_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.accounts (
    id bigint NOT NULL,
    balance numeric(19,4) NOT NULL,
    is_manual boolean NOT NULL,
    name character varying(100) NOT NULL,
    notes character varying(500),
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT accounts_type_check CHECK (((type)::text = ANY ((ARRAY['STOCK_PORTFOLIO'::character varying, 'CASH'::character varying, 'RETIREMENT'::character varying, 'EDUCATION'::character varying, 'OTHER'::character varying])::text[])))
);


ALTER TABLE public.accounts OWNER TO admin;

--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: digital_garden; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.digital_garden (
    id bigint NOT NULL,
    content text,
    created_at timestamp(6) without time zone,
    growth_stage character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT digital_garden_growth_stage_check CHECK (((growth_stage)::text = ANY ((ARRAY['SEEDLING'::character varying, 'BUDDING'::character varying, 'EVERGREEN'::character varying])::text[])))
);


ALTER TABLE public.digital_garden OWNER TO admin;

--
-- Name: digital_garden_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.digital_garden ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.digital_garden_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: family_pulse; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.family_pulse (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    notes character varying(255),
    primary_activity character varying(255),
    status character varying(255),
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.family_pulse OWNER TO admin;

--
-- Name: family_pulse_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.family_pulse ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.family_pulse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: garden_lifelog_links; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.garden_lifelog_links (
    note_id bigint NOT NULL,
    lifelog_id bigint NOT NULL
);


ALTER TABLE public.garden_lifelog_links OWNER TO admin;

--
-- Name: life_log; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.life_log (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    end_date date,
    external_id character varying(255),
    image_url character varying(255),
    intensity integer,
    key_takeaway character varying(500),
    metadata character varying(1000),
    rating integer,
    start_date date,
    status character varying(255),
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT life_log_status_check CHECK (((status)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'PLANNED'::character varying])::text[]))),
    CONSTRAINT life_log_type_check CHECK (((type)::text = ANY ((ARRAY['BOOK'::character varying, 'MOVIE'::character varying, 'SHOW'::character varying, 'ALBUM'::character varying, 'HOBBY'::character varying])::text[])))
);


ALTER TABLE public.life_log OWNER TO admin;

--
-- Name: life_log_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.life_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.life_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media_activity; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.media_activity (
    id bigint NOT NULL,
    completion_date date,
    cover_url character varying(255),
    created_at timestamp(6) without time zone,
    creator character varying(255),
    external_id character varying(255),
    genre character varying(255),
    media_type character varying(255),
    notes character varying(255),
    publisher character varying(255),
    rating integer,
    release_year integer,
    start_date date,
    status character varying(255),
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT media_activity_media_type_check CHECK (((media_type)::text = ANY ((ARRAY['BOOK'::character varying, 'MOVIE'::character varying, 'TV_SHOW'::character varying, 'PODCAST'::character varying, 'SONG'::character varying, 'ALBUM'::character varying, 'MAGAZINE'::character varying])::text[]))),
    CONSTRAINT media_activity_status_check CHECK (((status)::text = ANY ((ARRAY['CURRENTLY_ENGAGED'::character varying, 'COMPLETED'::character varying, 'PLANNED'::character varying, 'PAUSED'::character varying])::text[])))
);


ALTER TABLE public.media_activity OWNER TO admin;

--
-- Name: media_activity_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.media_activity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_activity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: paper_transactions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.paper_transactions (
    id bigint NOT NULL,
    notes character varying(500),
    price_per_share numeric(19,4) NOT NULL,
    quantity numeric(19,8) NOT NULL,
    symbol character varying(10) NOT NULL,
    transaction_date timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT paper_transactions_type_check CHECK (((type)::text = ANY ((ARRAY['BUY'::character varying, 'SELL'::character varying])::text[])))
);


ALTER TABLE public.paper_transactions OWNER TO admin;

--
-- Name: paper_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.paper_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.paper_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_images; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.post_images (
    social_media_post_id bigint NOT NULL,
    image_urls character varying(255)
);


ALTER TABLE public.post_images OWNER TO admin;

--
-- Name: quick_fact; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.quick_fact (
    key character varying(255) NOT NULL,
    category character varying(255),
    description character varying(255),
    external_id character varying(255),
    image_url character varying(255),
    is_enriched boolean,
    metadata text,
    source_url character varying(255),
    updated_at timestamp(6) without time zone,
    value character varying(255) NOT NULL
);


ALTER TABLE public.quick_fact OWNER TO admin;

--
-- Name: social_media_post; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.social_media_post (
    id bigint NOT NULL,
    caption character varying(255),
    comments text,
    content text,
    published_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.social_media_post OWNER TO admin;

--
-- Name: social_media_post_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.social_media_post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.social_media_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_tickers; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.stock_tickers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    notes character varying(500),
    purchase_price numeric(19,4) NOT NULL,
    quantity numeric(19,8) NOT NULL,
    symbol character varying(10) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    current_price numeric(19,4),
    daily_change numeric(19,4),
    daily_change_percentage numeric(10,4),
    is_market_open boolean,
    last_price_update timestamp(6) without time zone
);


ALTER TABLE public.stock_tickers OWNER TO admin;

--
-- Name: stock_tickers_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.stock_tickers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_tickers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_transactions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.stock_transactions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    notes character varying(500),
    price_per_share numeric(19,4) NOT NULL,
    quantity numeric(19,8) NOT NULL,
    symbol character varying(10) NOT NULL,
    total_cost numeric(19,4),
    transaction_date date NOT NULL,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT stock_transactions_type_check CHECK (((type)::text = ANY ((ARRAY['BUY'::character varying, 'SELL'::character varying])::text[])))
);


ALTER TABLE public.stock_transactions OWNER TO admin;

--
-- Name: stock_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.stock_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: upcoming_trip; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.upcoming_trip (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description text,
    destination character varying(255) NOT NULL,
    end_date date,
    planned_activities text,
    start_date date,
    status character varying(255),
    trip_type character varying(255),
    updated_at timestamp(6) without time zone,
    CONSTRAINT upcoming_trip_status_check CHECK (((status)::text = ANY ((ARRAY['PLANNED'::character varying, 'CONFIRMED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT upcoming_trip_trip_type_check CHECK (((trip_type)::text = ANY ((ARRAY['VACATION'::character varying, 'BUSINESS'::character varying, 'EVENT'::character varying, 'CONFERENCE'::character varying])::text[])))
);


ALTER TABLE public.upcoming_trip OWNER TO admin;

--
-- Name: upcoming_trip_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.upcoming_trip ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.upcoming_trip_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    password_hash character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    username character varying(50) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['GUEST'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO admin;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: watchlist_items; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.watchlist_items (
    id bigint NOT NULL,
    added_at timestamp(6) without time zone NOT NULL,
    notes character varying(200),
    symbol character varying(10) NOT NULL,
    target_price numeric(19,4),
    user_id bigint NOT NULL
);


ALTER TABLE public.watchlist_items OWNER TO admin;

--
-- Name: watchlist_items_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.watchlist_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.watchlist_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: account_balance_history; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.account_balance_history (id, account_id, balance, date, recorded_at) FROM stdin;
2	1	0.0000	2026-01-01	2026-02-01 01:12:47.964339
5	1	0.0000	2026-01-02	2026-02-01 01:12:47.964341
8	1	0.0000	2026-01-03	2026-02-01 01:12:47.964341
9	1	0.0000	2026-01-04	2026-02-01 01:12:47.964342
11	1	0.0000	2026-01-05	2026-02-01 01:12:47.964342
13	1	0.0000	2026-01-06	2026-02-01 01:12:47.964343
15	1	0.0000	2026-01-07	2026-02-01 01:12:47.964343
16	1	0.0000	2026-01-08	2026-02-01 01:12:47.964344
17	1	0.0000	2026-01-09	2026-02-01 01:12:47.964344
18	1	0.0000	2026-01-10	2026-02-01 01:12:47.964345
19	1	0.0000	2026-01-11	2026-02-01 01:12:47.964345
20	1	0.0000	2026-01-12	2026-02-01 01:12:47.964346
21	1	0.0000	2026-01-13	2026-02-01 01:12:47.964346
22	1	0.0000	2026-01-14	2026-02-01 01:12:47.964347
23	1	0.0000	2026-01-15	2026-02-01 01:12:47.964347
24	1	0.0000	2026-01-16	2026-02-01 01:12:47.964348
25	1	0.0000	2026-01-17	2026-02-01 01:12:47.964349
26	1	0.0000	2026-01-18	2026-02-01 01:12:47.964349
27	1	0.0000	2026-01-19	2026-02-01 01:12:47.96435
28	1	0.0000	2026-01-20	2026-02-01 01:12:47.96435
29	1	0.0000	2026-01-21	2026-02-01 01:12:47.964351
30	1	0.0000	2026-01-22	2026-02-01 01:12:47.964351
31	1	0.0000	2026-01-23	2026-02-01 01:12:47.964352
32	1	0.0000	2026-01-24	2026-02-01 01:12:47.964352
33	1	0.0000	2026-01-25	2026-02-01 01:12:47.964353
34	1	0.0000	2026-01-26	2026-02-01 01:12:47.964353
35	1	0.0000	2026-01-27	2026-02-01 01:12:47.964354
36	1	0.0000	2026-01-28	2026-02-01 01:12:47.964354
37	1	0.0000	2026-01-29	2026-02-01 01:12:47.964355
38	1	0.0000	2026-01-30	2026-02-01 01:12:47.964355
39	1	0.0000	2026-01-31	2026-02-01 01:12:47.964356
40	1	0.0000	2026-02-01	2026-02-01 01:12:47.964356
1	1	0.0000	2026-01-31	2026-02-01 01:12:47.959954
6	1	0.0000	2026-02-01	2026-02-01 01:12:47.959967
3	1	0.0000	2026-01-27	2026-02-01 01:12:47.976877
4	1	0.0000	2026-01-28	2026-02-01 01:12:47.976879
7	1	0.0000	2026-01-29	2026-02-01 01:12:47.976879
10	1	0.0000	2026-01-30	2026-02-01 01:12:47.97688
12	1	0.0000	2026-01-31	2026-02-01 01:12:47.97688
14	1	0.0000	2026-02-01	2026-02-01 01:12:47.97688
\.


--
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.accounts (id, balance, is_manual, name, notes, type, updated_at) FROM stdin;
1	0.0000	f	Stock Portfolio	\N	STOCK_PORTFOLIO	2026-01-26 03:06:29.038494
3	27478.8100	t	Roth IRA	\N	RETIREMENT	2026-01-26 03:06:29.062184
5	228876.1200	t	Amazon RSU	\N	OTHER	2026-01-26 03:06:29.062281
6	24866.6400	t	Evalyn's College Fund	\N	EDUCATION	2026-01-26 03:06:29.062288
7	23362.4500	t	Madelyn's College Fund	\N	EDUCATION	2026-01-26 03:06:29.062293
8	23682.8200	t	Nathan's College Fund	\N	EDUCATION	2026-01-26 03:06:29.062297
9	219013.7800	t	Thrift Savings Plan	\N	RETIREMENT	2026-01-26 03:06:29.062301
2	394828.3500	t	Fidelity Cash	\N	CASH	2026-01-26 03:27:33.902215
4	122618.6500	t	Amazon 401k	\N	OTHER	2026-01-26 03:37:44.624858
\.


--
-- Data for Name: digital_garden; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.digital_garden (id, content, created_at, growth_stage, title, updated_at) FROM stdin;
\.


--
-- Data for Name: family_pulse; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.family_pulse (id, name, notes, primary_activity, status, updated_at) FROM stdin;
1	Madelyn	Studying hard and making new friends	WSU Student	Doing great at college	2026-01-26 01:32:38.094298
2	Evalyn	Practicing parallel parking and highway driving	Learning to Drive	Getting more confident behind the wheel	2026-01-26 01:32:38.111084
3	Nate	Doing well in classes and enjoying team sports	School & Sports	Balancing academics and athletics	2026-01-26 01:32:38.112758
\.


--
-- Data for Name: garden_lifelog_links; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.garden_lifelog_links (note_id, lifelog_id) FROM stdin;
\.


--
-- Data for Name: life_log; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.life_log (id, created_at, end_date, external_id, image_url, intensity, key_takeaway, metadata, rating, start_date, status, title, type, updated_at) FROM stdin;
1	2026-01-26 01:42:27.592349	2026-01-08	\N	https://covers.openlibrary.org/b/id/14852090-L.jpg	\N	Nothing in here surprised me. Facebook execs are evil and self-absorbed.	{"title":"Careless People","isbn":null,"coverUrl":"https://covers.openlibrary.org/b/id/14852090-L.jpg","publisher":null,"description":null,"subjectsAsString":null,"authorsAsString":"Sarah Wynn-Williams","firstAuthor":"Sarah Wynn-Williams","author_name":["Sarah Wynn-Williams"],"cover_i":14852090,"first_publish_year":2025,"subject":null,"language":["eng"],"number_of_pages_median":null}	3	2026-01-01	PLANNED	Careless People	BOOK	2026-01-26 01:42:27.592357
2	2026-01-26 01:51:41.940559	2026-01-12	\N	https://covers.openlibrary.org/b/id/408133-L.jpg	\N	\N	{"title":"The Mote in God's Eye","isbn":null,"coverUrl":"https://covers.openlibrary.org/b/id/408133-L.jpg","publisher":null,"description":null,"subjectsAsString":null,"authorsAsString":"Larry Niven, Jerry Pournelle, L.J. Ganser","firstAuthor":"Larry Niven","author_name":["Larry Niven","Jerry Pournelle","L.J. Ganser"],"cover_i":408133,"first_publish_year":1974,"subject":null,"language":["eng","spa","fre"],"number_of_pages_median":null}	5	2026-01-07	COMPLETED	The Mote in God's Eye	BOOK	2026-01-26 01:51:41.940562
3	2026-01-26 02:04:35.895809	2026-01-16	\N	https://covers.openlibrary.org/b/id/11200092-L.jpg	\N	Outstanding, can't wait to see the movie	{"title":"Project Hail Mary","isbn":null,"coverUrl":"https://covers.openlibrary.org/b/id/11200092-L.jpg","publisher":null,"description":null,"subjectsAsString":null,"authorsAsString":"Andy Weir","firstAuthor":"Andy Weir","author_name":["Andy Weir"],"cover_i":11200092,"first_publish_year":2021,"subject":null,"language":["fin","spa","tur","ger","eng"],"number_of_pages_median":null}	5	2026-01-12	PLANNED	Project Hail Mary	BOOK	2026-01-26 02:04:35.895812
4	2026-01-26 02:05:50.572009	\N	\N	https://covers.openlibrary.org/b/id/15161980-L.jpg	\N	\N	{"title":"1929","isbn":null,"coverUrl":"https://covers.openlibrary.org/b/id/15161980-L.jpg","publisher":null,"description":null,"subjectsAsString":null,"authorsAsString":"Andrew Ross Sorkin","firstAuthor":"Andrew Ross Sorkin","author_name":["Andrew Ross Sorkin"],"cover_i":15161980,"first_publish_year":2025,"subject":null,"language":["eng"],"number_of_pages_median":null}	\N	2026-01-21	IN_PROGRESS	1929	BOOK	2026-01-26 02:05:50.572012
5	2026-01-26 02:06:34.807568	2026-01-23	\N	https://covers.openlibrary.org/b/id/15152898-L.jpg	\N	Too much romance	{"title":"Blood of Hercules","isbn":null,"coverUrl":"https://covers.openlibrary.org/b/id/15152898-L.jpg","publisher":null,"description":null,"subjectsAsString":null,"authorsAsString":"Jasmine Mas","firstAuthor":"Jasmine Mas","author_name":["Jasmine Mas"],"cover_i":15152898,"first_publish_year":2024,"subject":null,"language":["eng"],"number_of_pages_median":null}	3	2026-01-19	PLANNED	Blood of Hercules	BOOK	2026-01-26 02:06:34.807571
6	2026-02-01 00:16:16.415883	2026-01-30	\N	https://image.tmdb.org/t/p/w500/gbVwHl4YPSq6BcC92TQpe7qUTh6.jpg	\N	Nothing	{"id":1168190,"title":"The Wrecking Crew","overview":"Estranged half-brothers Jonny and James reunite after their father's mysterious death. As they search for the truth, buried secrets reveal a conspiracy threatening to tear their family apart.","adult":false,"popularity":584.6058,"director":null,"genre":null,"runtime":null,"imdbId":null,"budget":null,"revenue":null,"posterUrl":"https://image.tmdb.org/t/p/w500/gbVwHl4YPSq6BcC92TQpe7qUTh6.jpg","releaseYear":2026,"backdropUrl":"https://image.tmdb.org/t/p/w1280/e4OnHU8HNAhdS6C4Ypk6NA26kPQ.jpg","formattedRating":"6.4/10","original_title":"The Wrecking Crew","release_date":"2026-01-28","poster_path":"/gbVwHl4YPSq6BcC92TQpe7qUTh6.jpg","backdrop_path":"/e4OnHU8HNAhdS6C4Ypk6NA26kPQ.jpg","genre_ids":[28,35,80,9648],"vote_average":6.4,"vote_count":142,"original_language":"en","video":false}	\N	\N	PLANNED	The Wrecking Crew	MOVIE	2026-02-01 00:16:16.415886
\.


--
-- Data for Name: media_activity; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.media_activity (id, completion_date, cover_url, created_at, creator, external_id, genre, media_type, notes, publisher, rating, release_year, start_date, status, title, updated_at) FROM stdin;
\.


--
-- Data for Name: paper_transactions; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.paper_transactions (id, notes, price_per_share, quantity, symbol, transaction_date, type, user_id) FROM stdin;
\.


--
-- Data for Name: post_images; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.post_images (social_media_post_id, image_urls) FROM stdin;
\.


--
-- Data for Name: quick_fact; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.quick_fact (key, category, description, external_id, image_url, is_enriched, metadata, source_url, updated_at, value) FROM stdin;
Pissed about ICE executing American citizens	general	\N	\N	\N	f	\N	\N	2026-01-26 02:05:04.767148	Feeling completely hopeless watching armed thugs from our government murder peaceful protestors.
Survived another round of layoffs at Amazon	general	\N	\N	\N	f	\N	\N	2026-02-01 00:20:55.186869	Looks like this will just be a part of our life now here in Seattle. While other hubs are shielded and will even grow
\.


--
-- Data for Name: social_media_post; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.social_media_post (id, caption, comments, content, published_at, updated_at) FROM stdin;
1	\N	\N	Made it through the weekend. Not looking forward to work tomorrow.	2026-01-26 06:34:00.079338	2026-01-26 06:34:00.079341
\.


--
-- Data for Name: stock_tickers; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.stock_tickers (id, created_at, notes, purchase_price, quantity, symbol, updated_at, user_id, current_price, daily_change, daily_change_percentage, is_market_open, last_price_update) FROM stdin;
4	2026-01-26 01:32:38.212285	Invesco QQQ Trust ETF - Nasdaq 100 tracking ETF	341.2100	109.90300000	QQQ	2026-01-26 06:42:12.105801	1	\N	\N	\N	\N	\N
9	2026-01-26 06:42:12.123273	Restored via Recalculation	116.6400	0.46700000	TMUS	2026-01-26 06:42:12.123274	1	\N	\N	\N	\N	\N
5	2026-01-26 01:32:38.212285	CoreWeave Inc Class A - AI cloud infrastructure	78.8477	634.12800000	CRWV	2026-01-26 06:42:12.137792	1	\N	\N	\N	\N	\N
6	2026-01-26 01:32:38.212285	Archer Aviation Inc - Electric vertical takeoff aircraft	9.5700	5000.00000000	ACHR	2026-01-26 06:42:12.142356	1	\N	\N	\N	\N	\N
3	2026-01-26 01:32:38.212285	Arista Networks Inc - Cloud networking solutions	102.6500	600.00000000	ANET	2026-01-26 06:42:12.146453	1	\N	\N	\N	\N	\N
8	2026-01-26 01:32:38.212285	SoundHound AI Inc Class A - Voice AI technology	11.3600	2500.00000000	SOUN	2026-01-26 06:42:12.149831	1	\N	\N	\N	\N	\N
7	2026-01-26 01:32:38.212285	Intel Corporation - Semiconductor manufacturer	53.9063	906.67200000	INTC	2026-01-26 06:42:12.15256	1	\N	\N	\N	\N	\N
2	2026-01-26 01:32:38.212285	SoFi Technologies Inc - Digital financial services platform	16.3500	3500.00000000	SOFI	2026-01-26 06:42:12.156164	1	\N	\N	\N	\N	\N
1	2026-01-26 01:32:38.212285	Amazon.com Inc - E-commerce and cloud computing giant	190.8871	3362.00000000	AMZN	2026-01-26 06:42:12.159202	1	\N	\N	\N	\N	\N
\.


--
-- Data for Name: stock_transactions; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.stock_transactions (id, created_at, notes, price_per_share, quantity, symbol, total_cost, transaction_date, type, user_id) FROM stdin;
1	2026-01-26 02:39:43.002063	Historical Import	9.5700	5000.00000000	ACHR	47850.0000	2025-02-20	BUY	1
2	2026-01-26 02:39:43.024261	Historical Import	231.4900	434.00000000	AMZN	100466.6600	2025-11-17	BUY	1
3	2026-01-26 02:39:43.025668	Historical Import	204.2100	403.00000000	AMZN	82296.6300	2025-05-15	BUY	1
4	2026-01-26 02:39:43.026711	Historical Import	198.4700	257.00000000	AMZN	51006.7900	2024-11-21	BUY	1
5	2026-01-26 02:39:43.027998	Historical Import	203.1000	639.00000000	AMZN	129780.9000	2024-11-15	BUY	1
6	2026-01-26 02:39:43.029242	Historical Import	181.5200	257.00000000	AMZN	46650.6400	2024-05-21	BUY	1
7	2026-01-26 02:39:43.03076	Historical Import	184.3500	635.00000000	AMZN	117062.2500	2024-05-15	BUY	1
8	2026-01-26 02:39:43.031788	Historical Import	175.4400	321.00000000	AMZN	56316.2400	2024-03-15	BUY	1
9	2026-01-26 02:39:43.032752	Historical Import	144.4200	45.00000000	AMZN	6498.9000	2023-11-15	BUY	1
10	2026-01-26 02:39:43.033531	Historical Import	141.2200	348.00000000	AMZN	49144.5600	2023-09-15	BUY	1
11	2026-01-26 02:39:43.034362	Historical Import	110.3800	23.00000000	AMZN	2538.7400	2023-05-15	BUY	1
12	2026-01-26 02:39:43.035242	Historical Import	102.6500	600.00000000	ANET	61590.0000	2025-02-19	BUY	1
13	2026-01-26 02:39:43.036006	Historical Import	78.8400	148.00000000	CRWV	11668.3200	2025-11-14	BUY	1
14	2026-01-26 02:39:43.036901	Historical Import	78.8900	1.00000000	CRWV	78.8900	2025-11-14	BUY	1
15	2026-01-26 02:39:43.038059	Historical Import	78.8300	0.12800000	CRWV	10.0902	2025-11-14	BUY	1
16	2026-01-26 02:39:43.039434	Historical Import	78.8500	485.00000000	CRWV	38242.2500	2025-11-14	BUY	1
17	2026-01-26 02:39:43.041528	Historical Import	48.9100	0.67200000	INTC	32.8675	2021-10-29	BUY	1
18	2026-01-26 02:39:43.042348	Historical Import	48.9100	306.00000000	INTC	14966.4600	2021-10-29	BUY	1
19	2026-01-26 02:39:43.043142	Historical Import	56.4600	600.00000000	INTC	33876.0000	2021-05-10	BUY	1
20	2026-01-26 02:39:43.043921	Historical Import	341.2100	0.90300000	QQQ	308.1126	2022-01-24	BUY	1
21	2026-01-26 02:39:43.044771	Historical Import	341.2100	109.00000000	QQQ	37191.8900	2022-01-24	BUY	1
22	2026-01-26 02:39:43.045634	Historical Import	16.3500	3500.00000000	SOFI	57225.0000	2025-02-19	BUY	1
23	2026-01-26 02:39:43.046773	Historical Import	11.3600	2500.00000000	SOUN	28400.0000	2025-02-19	BUY	1
24	2026-01-26 02:39:43.047665	Historical Import	116.6400	0.46700000	TMUS	54.4709	2021-11-17	BUY	1
\.


--
-- Data for Name: upcoming_trip; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.upcoming_trip (id, created_at, description, destination, end_date, planned_activities, start_date, status, trip_type, updated_at) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.users (id, created_at, password_hash, role, updated_at, username) FROM stdin;
1	2026-01-26 01:32:38.201329	$2a$10$8rGbQciSMC8QWBONbMpJ9eHobskpGnJnBTAzShDVctAktDSZce/.G	ADMIN	2026-01-26 01:32:38.201336	admin
\.


--
-- Data for Name: watchlist_items; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.watchlist_items (id, added_at, notes, symbol, target_price, user_id) FROM stdin;
\.


--
-- Name: account_balance_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.account_balance_history_id_seq', 40, true);


--
-- Name: accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.accounts_id_seq', 9, true);


--
-- Name: digital_garden_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.digital_garden_id_seq', 1, false);


--
-- Name: family_pulse_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.family_pulse_id_seq', 3, true);


--
-- Name: life_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.life_log_id_seq', 6, true);


--
-- Name: media_activity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.media_activity_id_seq', 1, false);


--
-- Name: paper_transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.paper_transactions_id_seq', 1, false);


--
-- Name: social_media_post_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.social_media_post_id_seq', 1, true);


--
-- Name: stock_tickers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.stock_tickers_id_seq', 9, true);


--
-- Name: stock_transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.stock_transactions_id_seq', 24, true);


--
-- Name: upcoming_trip_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.upcoming_trip_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.users_id_seq', 1, true);


--
-- Name: watchlist_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.watchlist_items_id_seq', 1, false);


--
-- Name: account_balance_history account_balance_history_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.account_balance_history
    ADD CONSTRAINT account_balance_history_pkey PRIMARY KEY (id);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: digital_garden digital_garden_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.digital_garden
    ADD CONSTRAINT digital_garden_pkey PRIMARY KEY (id);


--
-- Name: family_pulse family_pulse_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.family_pulse
    ADD CONSTRAINT family_pulse_pkey PRIMARY KEY (id);


--
-- Name: garden_lifelog_links garden_lifelog_links_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.garden_lifelog_links
    ADD CONSTRAINT garden_lifelog_links_pkey PRIMARY KEY (note_id, lifelog_id);


--
-- Name: life_log life_log_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.life_log
    ADD CONSTRAINT life_log_pkey PRIMARY KEY (id);


--
-- Name: media_activity media_activity_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.media_activity
    ADD CONSTRAINT media_activity_pkey PRIMARY KEY (id);


--
-- Name: paper_transactions paper_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.paper_transactions
    ADD CONSTRAINT paper_transactions_pkey PRIMARY KEY (id);


--
-- Name: quick_fact quick_fact_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.quick_fact
    ADD CONSTRAINT quick_fact_pkey PRIMARY KEY (key);


--
-- Name: social_media_post social_media_post_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.social_media_post
    ADD CONSTRAINT social_media_post_pkey PRIMARY KEY (id);


--
-- Name: stock_tickers stock_tickers_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.stock_tickers
    ADD CONSTRAINT stock_tickers_pkey PRIMARY KEY (id);


--
-- Name: stock_transactions stock_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.stock_transactions
    ADD CONSTRAINT stock_transactions_pkey PRIMARY KEY (id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: upcoming_trip upcoming_trip_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.upcoming_trip
    ADD CONSTRAINT upcoming_trip_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: watchlist_items watchlist_items_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.watchlist_items
    ADD CONSTRAINT watchlist_items_pkey PRIMARY KEY (id);


--
-- Name: idx_account_type; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_account_type ON public.accounts USING btree (type);


--
-- Name: idx_hist_account_id; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_hist_account_id ON public.account_balance_history USING btree (account_id);


--
-- Name: idx_hist_date; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_hist_date ON public.account_balance_history USING btree (date);


--
-- Name: idx_paper_user_id; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_paper_user_id ON public.paper_transactions USING btree (user_id);


--
-- Name: idx_stock_created_at; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_stock_created_at ON public.stock_tickers USING btree (created_at);


--
-- Name: idx_stock_symbol; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_stock_symbol ON public.stock_tickers USING btree (symbol);


--
-- Name: idx_stock_user_id; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_stock_user_id ON public.stock_tickers USING btree (user_id);


--
-- Name: idx_stock_user_symbol; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_stock_user_symbol ON public.stock_tickers USING btree (user_id, symbol);


--
-- Name: idx_txn_date; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_txn_date ON public.stock_transactions USING btree (transaction_date);


--
-- Name: idx_txn_symbol; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_txn_symbol ON public.stock_transactions USING btree (symbol);


--
-- Name: idx_txn_user_id; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_txn_user_id ON public.stock_transactions USING btree (user_id);


--
-- Name: idx_watchlist_symbol; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_watchlist_symbol ON public.watchlist_items USING btree (symbol);


--
-- Name: idx_watchlist_user_id; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_watchlist_user_id ON public.watchlist_items USING btree (user_id);


--
-- Name: garden_lifelog_links fkg9qsvqr08o3221aj5srl2p5se; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.garden_lifelog_links
    ADD CONSTRAINT fkg9qsvqr08o3221aj5srl2p5se FOREIGN KEY (lifelog_id) REFERENCES public.life_log(id);


--
-- Name: post_images fkh67auxqq41aeihom0gb3kwxuc; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.post_images
    ADD CONSTRAINT fkh67auxqq41aeihom0gb3kwxuc FOREIGN KEY (social_media_post_id) REFERENCES public.social_media_post(id);


--
-- Name: garden_lifelog_links fktodfscewasw1gleshpdgnsoxo; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.garden_lifelog_links
    ADD CONSTRAINT fktodfscewasw1gleshpdgnsoxo FOREIGN KEY (note_id) REFERENCES public.digital_garden(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 97fezhCafcBjGRABVOCpnOI6PDaQ9fGk2hqa6mB31tWM5UEfccnKVWaf2Cj7soe

